<ul id="menu" class="page-sidebar-menu">

    @if( Sentinel::inRole('admin') )
    <li {!! (Request::is('admin/users') || Request::is('admin/users/create') || Request::is('admin/user_profile') || Request::is('admin/users/*') || Request::is('admin/deleted_users') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="user" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">{{trans('__title.layouts.users')}}</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('admin/users') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/users') }}">
                    <i class="fa fa-angle-double-right"></i>
                    {{trans('__title.layouts.users')}}
                </a>
            </li>
            <li {!! (Request::is('admin/users/create') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/users/create') }}">
                    <i class="fa fa-angle-double-right"></i>
                    {{trans('__title.layouts.add_user')}}
                </a>
            </li>
        </ul>
    </li>
    @endif

    <li {!! (Request::is('admin/clients') || Request::is('admin/clients/create') || Request::is('admin/clients/*') || Request::is('admin/bills/create') || Request::is('admin/bills/*') ? 'class="active"' : '') !!}>
        <a href="#">
            <i class="livicon" data-name="table" data-size="18" data-c="#e9573f" data-hc="#e9573f"
               data-loop="true"></i>
            <span class="title">{{trans('__title.layouts.statistical_table')}}</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li {!! (Request::is('admin/clients') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/clients') }}">
                    <i class="fa fa-angle-double-right"></i>
                    {{trans('__title.layouts.clients')}}
                </a>
            </li>
            @if( Sentinel::inRole('admin') )
            <li {!! (Request::is('admin/clients/create') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/clients/create') }}">
                    <i class="fa fa-angle-double-right"></i>
                    {{trans('__title.layouts.add_client')}}
                </a>
            </li>
            <li {!! (Request::is('admin/bills/create/*') ? 'class="active" id="active"' : '') !!}>
                <a href="{{ URL::to('admin/bills/create/0') }}">
                    <i class="fa fa-angle-double-right"></i>
                    {{trans('__title.layouts.add_bill')}}
                </a>
            </li>
            @endif
        </ul>
    </li>
    

    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>